version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper_1
    ports:
      - "2181:2181"
    networks:
      - docker_net
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_1:2181
      ZK: zookeeper_1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"
